name: Docs Composite Action
on:
  workflow_call:

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1
        with:
          ref: ${{ github.event.repository.default_branch }}

      # https://github.com/tmknom/actdocs
      - name: Inject document
        env:
          YAML_FILE: action.yml
          MD_FILE: README.md
        run: |
          set -x
          docker run --rm -v "$(pwd):/work" -w "/work" \
          ghcr.io/tmknom/actdocs inject --sort \
          --file "${MD_FILE}" "${YAML_FILE}"

      - name: Git Push
        id: push
        uses: tmknom/git-push-action@600da3868b2ab03e581b51e02405adceeabeda31 # v0.4.0
        with:
          message: 'docs: update README using actdocs'

      - name: Create Pull Request
        if: ${{ steps.push.outputs.pushed == 'true' }}
        uses: tmknom/create-pull-request-action@v0
        with:
          head-branch: ${{ steps.push.outputs.branch }}
          title: ${{ steps.push.outputs.subject }}
          body: ${{ steps.push.outputs.body }}
