name: Docs Composite Action
on:
  workflow_call:

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      pull-requests: write
    env:
      BASE_BRANCH: ${{ github.event.repository.default_branch }}
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1
        with:
          ref: ${{ env.BASE_BRANCH }}

      # https://github.com/tmknom/actdocs
      - name: Inject document
        env:
          YAML_FILE: action.yml
          MD_FILE: README.md
        run: |
          set -x
          docker run --rm -v "$(pwd):/work" -w "/work" \
          ghcr.io/tmknom/actdocs inject --sort \
          --file "${MD_FILE}" "${YAML_FILE}"

      - name: Git Push
        id: push
        uses: tmknom/git-push-action@d88b186c540e4179bbb8e228b9c09e1a45677be7 # v0.2.1

      - name: Create PR
        if: ${{ steps.push.outputs.pushed == 'true' }}
        env:
          BRANCH: ${{ steps.push.outputs.branch }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          set -x
          gh pr create --base "${BASE_BRANCH}" --head "${BRANCH}" --fill-first
